helmDefaults:
  atomic: false # want to be able to inspect pods if they fail in dev so false
  cleanupOnFail: false # want to be able to inspect pods if they fail in dev so false
  timeout: 900
  force: true 
  verify: false # MUST BE FALSE. true is broken on helm 3 https://github.com/roboll/helmfile/issues/11

repositories:
  - name: dasmeta
    url: https://dasmeta.github.io/helm/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard

templates:
  common: &common
    missingFileHandler: Warn
    values:
      - ./{{ .Release.Name }}.yaml.gotmpl
  dasmeta: &dasmeta
    <<: *common
    chart: dasmeta/{{ .Release.Name }}
  bitnami: &bitnami
    <<: *common
    chart: bitnami/{{ .Release.Name }}
